### ISSUE TITLE
New picture for my website

### ISSUE THREAD

**Issue by rebeccarubenstein** [nevanscott/rebeccarubenstein.com#2]
Thinking it's time for a pic change (as much as I'm fond of that years-old photo of me sippin' on a milkshake). Happy to do this myself if I'm able - I just need to know how to make it happen so I don't mess up the code. Going to attach a new pic, which will probably need to be resized to fit in the current circular format.

![sassy](https://user-images.githubusercontent.com/4043562/30135507-d9344864-930f-11e7-8eef-4703bbdfb297.jpg)

**Comment by rebeccarubenstein** [comment]
This is also an option for a new photo, in case you think the other one is too saturated with light and this one might seem friendlier, maybe... I'll let you make the call on this; you tend to have better judgment of these things. :)

![rubensteinpic](https://user-images.githubusercontent.com/4043562/30135582-3926ea88-9310-11e7-9faf-4b918f56a50a.jpg)

**Comment by nevanscott** [comment]
Overall I think the first one looks better, but it's not doing great on the white background. Hmmm... I might add a little border around it or something.
